title: 吴振宇@北邮
logo: /img/person.jpg
description: <b>研究方向：</b>工业大数据分析、故障预测与健康管理（PHM）、机器学习、深度学习 <br/><b>办公地址：</b>北京邮电大学新科研楼818<br/> <b>联系方式：</b>shower0512@bupt.edu.cn
google_analytics: 
show_downloads: false
theme: jekyll-theme-minimal
gems:
  - jekyll-mentions